name: Publish

on:
  release:
    types:
    - created

jobs:
  build-and-release:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install
    - name: Compile
      run: npm run compile
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: npm run deploy
      env:
       VSCE_PAT: ${{ secrets.VSCE_PAT }}
